export default {
  ac: 'alignContent',
  ai: 'alignItems',
  as: 'alignSelf',
  bg: 'backgroundColor',
  bottom: 'bottom',
  br: 'borderRadius',
  brb: [
    'borderRadiusBottomRight',
    'borderRadiusBottomLeft',
  ],
  brbl: 'borderRadiusBottomLeft',
  brbr: 'borderRadiusBottomRight',
  brl: [
    'borderRadiusBottomLeft',
    'borderRadiusTopLeft',
  ],
  brr: [
    'borderRadiusBottomRight',
    'borderRadiusTopRight',
  ],
  brt: [
    'borderRadiusTopRight',
    'borderRadiusTopLeft',
  ],
  brtl: 'borderRadiusTopLeft',
  brtr: 'borderRadiusTopRight',
  brx: [
    'borderRadiusLeft',
    'borderRadiusRight',
  ],
  bry: [
    'borderRadiusTop',
    'borderRadiusBottom',
  ],
  c: 'color',
  cur: 'cursor',
  d: 'display',
  f: 'fontSize',
  ff: 'fontFamily',
  fl: 'float',
  flxb: 'flexBasis',
  flxd: 'flexDirection',
  flxg: 'flexGrow',
  flxs: 'flexShrink',
  flxw: 'flexWrap',
  fs: 'fontSize',
  fw: 'fontWeight',
  h: 'height',
  jc: 'justifyContent',
  left: 'left',
  lh: 'lineHeight',
  ls: 'letterSpacing',
  lst: 'listStyleType',
  m: 'margin',
  mb: 'marginBottom',
  ml: 'marginLeft',
  mr: 'marginRight',
  mt: 'marginTop',
  mx: [
    'marginLeft',
    'marginRight',
  ],
  my: [
    'marginTop',
    'marginBottom',
  ],
  o: 'overflow',
  op: 'opacity',
  ox: 'overflowX',
  oy: 'overflowY',
  p: 'padding',
  pb: 'paddingBottom',
  pl: 'paddingLeft',
  pos: 'position',
  pr: 'paddingRight',
  pt: 'paddingTop',
  px: [
    'paddingRight',
    'paddingLeft',
  ],
  py: [
    'paddingTop',
    'paddingBottom',
  ],
  right: 'right',
  ta: 'textAlign',
  td: 'textDecoration',
  tdc: 'textDecorationColor',
  top: 'top',
  tt: 'textTransform',
  va: 'verticalAlign',
  w: 'width',
  ws: 'whiteSpace',
  zi: 'zIndex',
};
